name: Rust

on:
  workflow_run:
    workflows: ["Tag Creation"]  # Name of the first workflow
    types:
      - completed  # Runs when the Release workflow completes successfully

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4

    - name: Install cross
      run: cargo install cross

    - name: Build for arm (Raspberry Pi 32-bit)
      run: cross build --release --target arm-unknown-linux-gnueabihf

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: target/arm-unknown-linux-gnueabihf/release/stocker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
