name: Create and Tag Release

on:
  push:
    branches:
      - main  # Adjust this to your default branch

permissions:
  contents: write

jobs:
  check-and-create-tag:
    runs-on: ubuntu-latest
    outputs: 
      tag_name: ${{ steps.step2.outputs.tag_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Version from Cargo.toml
        id: read-version
        run: |
          cd app
          version=$(grep '^version' Cargo.toml | sed 's/version = "//;s/"//')
          echo "VERSION=$version" >> $GITHUB_ENV  # Set environment variable with the version
          echo "tag_name=v$version" >> $GITHUB_OUTPUT  # Set the tag_name output variable

      - name: Verify Tag Does Not Exist
        id: verify-tag
        run: |
          if git tag | grep -q "v${{ env.VERSION }}"; then
            echo "Tag v${{ env.VERSION }} already exists. Skipping tag creation."
            exit 1
          fi

      - name: Create and Push New Tag
        if: ${{ success() }}
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ env.VERSION }}

  build-release-artifacts:
    needs: check-and-create-tag
    name: Build Release Artifacts
    uses: ./.github/workflows/rust.yml  # Call the Rust-based workflow
    with:
      tag_name: ${{ needs.check-and-create-tag.outputs.tag_name }}  # Pass the tag_name from the first job
